catalog_templates:
- channels:
  - alpha
  replaces: openstack-lightspeed-operator.v0.0.2
  template_name: v4.16.yaml
- channels:
  - alpha
  replaces: openstack-lightspeed-operator.v0.0.2
  template_name: v4.18.yaml
