---
################################
## Airflow Worker ServiceAccount
#################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: annotationlab-worker
  labels:
    tier: airflow
    component: worker
    release: annotationlab
    chart: "airflow-1.0.0"
    heritage: Helm
