apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nlp-server-role-binding
subjects:
  - kind: ServiceAccount
    name: nlp-server-sa
roleRef:
  kind: Role
  name: nlp-server-role
  apiGroup: rbac.authorization.k8s.io
apiVersion: rbac.authorization.k8s.io/v1
