apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    operator: volume-expander-operator
  name: volume-expander-operator-controller-manager-metrics-monitor
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    tlsConfig:
      ca:
        secret:
          key: tls.crt
          name: volume-expander-operator-certs
          optional: false
      serverName: volume-expander-operator-controller-manager-metrics.volume-expander-operator.svc
  selector:
    matchLabels:
      operator: volume-expander-operator
