apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
           "apiVersion": "agent-install.openshift.io/v1beta1",
           "kind": "AgentServiceConfig",
           "metadata": {
              "namespace": "assisted-installer",
              "name": "agent"
           },
           "spec": {
              "databaseStorage": {
                 "accessModes": [
                    "ReadWriteOnce"
                 ],
                 "resources": {
                    "requests": {
                       "storage": "10Gi"
                    }
                 }
              },
              "filesystemStorage": {
                 "accessModes": [
                    "ReadWriteOnce"
                 ],
                 "resources": {
                    "requests": {
                       "storage": "100Gi"
                    }
                 }
              }
           }
        }
      ]
    capabilities: Basic Install
    categories: OpenShift Optional
    description: Assisted Service is used to orchestrate baremetal OpenShift installations.
    operatorframework.io/suggested-namespace: assisted-installer
    operators.operatorframework.io/builder: operator-sdk-v1.4.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: https://github.com/openshift/assisted-service
    support: https://github.com/openshift/assisted-service/issues/new
    createdAt: '2021-04-16T08:00:00Z'
    containerImage: quay.io/ocpmetal/assisted-service@sha256:330245cb266d2cc53fa0009fe949b0667cbaef3f72a548735734caf5c553eec6
    olm.skipRange: "<0.0.2"
  name: assisted-service-operator.v0.0.2
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: AgentServiceConfig
      kind: AgentServiceConfig
      name: agentserviceconfigs.agent-install.openshift.io
      version: v1beta1
    - displayName: Agent
      kind: Agent
      name: agents.agent-install.openshift.io
      version: v1beta1
    - displayName: InfraEnv
      kind: InfraEnv
      name: infraenvs.agent-install.openshift.io
      version: v1beta1
    - displayName: NMStateConfig
      kind: NMStateConfig
      name: nmstateconfigs.agent-install.openshift.io
      version: v1beta1
  description: |-
    Assisted Service is used to orchestrate baremetal OpenShift installations.

    When creating the AgentServiceConfig CR. It is important to note that the
    controller will only ever reconcile an AgentServiceConfig named "agent".
    No other name will be accepted.
  displayName: Assisted Service Operator
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - nodes
          - pods
          - endpoints
          - services
          - secrets
          verbs:
          - get
          - watch
          - list
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - watch
          - list
          - create
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - get
          - watch
          - list
          - delete
          - create
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - get
          - list
          - watch
        - apiGroups:
          - config.openshift.io
          resources:
          - clusterversions
          verbs:
          - get
          - list
        - apiGroups:
          - ""
          resourceNames:
          - assisted-service-leader-election-helper
          - assisted-service-migration-helper
          - assisted-service-baseiso-helper
          resources:
          - configmaps
          verbs:
          - get
          - update
          - delete
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - get
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - agent-install.openshift.io
          resources:
          - agents
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - agent-install.openshift.io
          resources:
          - agents/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - agent-install.openshift.io
          resources:
          - agentserviceconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - agent-install.openshift.io
          resources:
          - agentserviceconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - agent-install.openshift.io
          resources:
          - agentserviceconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - agent-install.openshift.io
          resources:
          - infraenvs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - agent-install.openshift.io
          resources:
          - infraenvs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - agent-install.openshift.io
          resources:
          - nmstateconfigs
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - hive.openshift.io
          resources:
          - clusterdeployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - hive.openshift.io
          resources:
          - clusterdeployments/finalizers
          verbs:
          - update
        - apiGroups:
          - hive.openshift.io
          resources:
          - clusterdeployments/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - metal3.io
          resources:
          - baremetalhosts
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: assisted-service-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: assisted-service-operator
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: assisted-service-operator
            spec:
              containers:
              - args:
                - --leader-elect
                command:
                - /assisted-service-operator
                env:
                - name: SERVICE_IMAGE
                  value: quay.io/ocpmetal/assisted-service@sha256:330245cb266d2cc53fa0009fe949b0667cbaef3f72a548735734caf5c553eec6
                - name: DATABASE_IMAGE
                  value: quay.io/ocpmetal/postgresql-12-centos7@sha256:94727d70e0afbf4e167e078744f3a10ac9d82edc553d57b0ecbb5443264f07e1
                - name: AGENT_IMAGE
                  value: quay.io/ocpmetal/assisted-installer-agent@sha256:d5da56e329a87d8729c80fa9a7ddd221c10a9fddf39df6e909bb99dfee79fa2c
                - name: CONTROLLER_IMAGE
                  value: quay.io/ocpmetal/assisted-installer-controller@sha256:11094031bf79dce9d21ed6efed12af4dab9f7002bdac14b68283a29811048756
                - name: INSTALLER_IMAGE
                  value: quay.io/ocpmetal/assisted-installer@sha256:badacb6c9764c3d79cb4067941128601954edeade8f86e65c33c68bf5c7d4d18
                - name: OPENSHIFT_VERSIONS
                  value: '{"4.6":{"display_name":"4.6.16","release_image":"quay.io/openshift-release-dev/ocp-release:4.6.16-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso","rhcos_version":"46.82.202012051820-0","support_level":"production"},"4.7":{"display_name":"4.7.5","release_image":"quay.io/openshift-release-dev/ocp-release:4.7.5-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.0/rhcos-4.7.0-x86_64-live.x86_64.iso","rhcos_version":"47.83.202102090044-0","support_level":"production"}}'
                - name: SERVICE_ACCOUNT_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.serviceAccountName
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/ocpmetal/assisted-service@sha256:330245cb266d2cc53fa0009fe949b0667cbaef3f72a548735734caf5c553eec6
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  requests:
                    cpu: 100m
                    memory: 200Mi
                securityContext:
                  allowPrivilegeEscalation: false
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - assisted-service
  - assisted-installer
  - OpenShift
  links:
  - name: Assisted Service
    url: https://github.com/openshift/assisted-service
  maintainers:
  - email: support@redhat.com
    name: Support
  maturity: alpha
  provider:
    name: Red Hat
  replaces: assisted-service-operator.v0.0.1
  version: 0.0.2
