apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: gitwebhook-operator-certs
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: gitwebhook-operator
    app.kubernetes.io/instance: gitwebhook-operator-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: gitwebhook-operator
    control-plane: gitwebhook-operator
  name: gitwebhook-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: gitwebhook-operator
status:
  loadBalancer: {}
