---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: embercsis.ember-csi.io
spec:
  group: ember-csi.io
  names:
    kind: EmberStorageBackend
    listKind: EmberStorageBackendList
    plural: embercsis
    singular: embercsi
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: EmberStorageBackend is the Schema for the embercsis API
