apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: apicurito
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: apicurito-operator-installer
rules:
- apiGroups:
  - apicur.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - deletecollection
  - watch
  - patch
