apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dbaas-prometheus
    control-plane: controller-manager
  name: dbaas-operator-controller-manager-metrics-service
spec:
  ports:
  - name: metrics
    port: 8443
    targetPort: metrics
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
