organization: community-operators

maintainers:
  - Allda
  - ezopezo
  - haripate
  - mporrato
  - tomasbakk

tests:
  - name: DeployableByOLM
    ignore_operators:
      - ^ack-.*
      - ^community-windows-machine-config-operator
  - name: check_dangling_bundles
    ignore_operators:
      - ^assisted-service-operator
  - name: check_operator_name
    ignore_operators:
      - ^ibm-block-csi-operator-community
      - ^postgresql
