apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: aws-neuron
    app.kubernetes.io/name: aws-neuron
    app.kubernetes.io/part-of: aws-neuron
  name: awslabs-gpu-operator-neuron-scheduler-extension
spec:
  ports:
  - name: http
    port: 12345
    targetPort: 12345
  selector:
    app.kubernetes.io/component: aws-neuron
    app.kubernetes.io/instance: neuron-scheduler-extension
    app.kubernetes.io/name: aws-neuron
    app.kubernetes.io/part-of: aws-neuron
status:
  loadBalancer: {}
