apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "cache.wunicorns.com/v1alpha1",
          "kind": "NodeDiscovery",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "node-discovery-operator",
              "app.kubernetes.io/instance": "nodediscovery-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "nodediscovery",
              "app.kubernetes.io/part-of": "node-discovery-operator"
            },
            "name": "nodediscovery-sample"
          },
          "spec": {
            "containers": [
              {
                "args": [
                  "tail",
                  "-f",
                  "/dev/null"
                ],
                "image": "alicek106/stress",
                "imagePullPolicy": "IfNotPresent",
                "name": "stress",
                "resources": {
                  "limits": {
                    "cpu": "100m",
                    "memory": "1000Mi"
                  },
                  "requests": {
                    "cpu": "100m",
                    "memory": "1000Mi"
                  }
                },
                "terminationGracePeriodSeconds": 10
              }
            ],
            "cpus": "0",
            "enabled": "true",
            "mems": "0",
            "nodeName": "worker3"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-06-18T01:32:51Z"
    operators.operatorframework.io/builder: operator-sdk-v1.31.0-ocp
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: node-discovery-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NodeDiscovery is the Schema for the nodediscoveries API
      displayName: Node Discovery
      kind: NodeDiscovery
      name: nodediscoveries.cache.wunicorns.com
      version: v1alpha1
  description: find cgroup infor and set value.
  displayName: cgroup-discovery-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - cache.wunicorns.com
          resources:
          - nodediscoveries
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cache.wunicorns.com
          resources:
          - nodediscoveries/finalizers
          verbs:
          - update
        - apiGroups:
          - cache.wunicorns.com
          resources:
          - nodediscoveries/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: node-discovery-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: node-discovery-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: node-discovery-operator
          control-plane: controller-manager
        name: node-discovery-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/caspell/cgroup-discovery@sha256:b437dcde0107124e43a4e2fb8026ec191f44b5e761bedc2c295f47ff489cf343
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: node-discovery-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: node-discovery-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cgroup
  - cpulist
  - mems
  - cpus
  - numa
  links:
  - name: Node Discovery Operator
    url: https://node-discovery-operator.domain
  maturity: alpha
  provider:
    name: minhokim
  version: 0.0.1
