apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: vault-config-operator
  name: vault-config-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: vault-config-operator
status:
  loadBalancer: {}
