apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: ibs.automotive.sig.centos.org
spec:
  group: automotive.sig.centos.org
  names:
    kind: ImageBuild
    listKind: ImageBuilds
    plural: ibs
    singular: ib
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: ImageBuild is the Schema for the imagebuilds API
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of ImageBuild
            properties:
              automotive_osbuild_image:
                type: string
              branch:
                default: main
                type: string
              git_url:
                type: string
              github:
                type: boolean
              gitlab:
                type: boolean
              nightly_build:
                properties:
                  build_command:
                    description: Build command to run for nightly builds
                    type: string
                  enabled:
                    type: boolean
                  schedule:
                    description: Cron schedule for nightly builds (e.g., '0 2 * *
                      *' for 2 AM daily)
                    type: string
                type: object
              repo_type:
                enum:
                - automotive-image-builder
                - sample-images
                type: string
              storage_class:
                type: string
              target_registry_image:
                description: Target registry image for this repository
                type: string
            required:
            - git_url
            - repo_type
            - target_registry_image
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of ImageBuild
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
