---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/part-of: coherence-operator
    app.kubernetes.io/version: 3.5.0
    control-plane: coherence
  name: coherence-operator-coherence-webhook-server-cert
