apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: controller-manager
    crowdstrike.com/component: kube-rbac-proxy
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: controller-manager-metrics-service
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: service
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  name: falcon-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
