catalog_templates:
- template_name: v4.17.yaml
  channels:
  - stable
  replaces: rabbitmq-messaging-topology-operator.v1.18.3
- template_name: v4.18.yaml
  channels:
  - stable
  replaces: rabbitmq-messaging-topology-operator.v1.18.3
- template_name: v4.19.yaml
  channels:
  - stable
  replaces: rabbitmq-messaging-topology-operator.v1.18.3
- template_name: v4.20.yaml
  channels:
  - stable
  replaces: rabbitmq-messaging-topology-operator.v1.18.3
- template_name: v4.21.yaml
  channels:
  - stable
  replaces: rabbitmq-messaging-topology-operator.v1.18.3
