apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: namespace-configuration-operator
  name: namespace-configuration-operator-controller-manager-metrics-monitor
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    tlsConfig:
      ca:
        secret:
          key: tls.crt
          name: namespace-configuration-operator-certs
          optional: false
      serverName: namespace-configuration-operator-metrics-service.namespace-configuration-operator.svc
  selector:
    matchLabels:
      control-plane: namespace-configuration-operator
