apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-engine-operator-webhook
  creationTimestamp: null
  name: multicluster-engine-operator-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: backplane-operator
status:
  loadBalancer: {}
