---
catalog_templates:
- template_name: v4.16.yaml
  channels:
  - alpha
  replaces: openstack-lightspeed-operator.v0.0.1
- template_name: v4.18.yaml
  channels:
  - alpha
  replaces: openstack-lightspeed-operator.v0.0.1
