apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaconnections-sbo-view
  labels:
    service.binding/controller: "true"
rules:
  - apiGroups:
      - rhoas.redhat.com
    resources:
      - kafkaconnections
    verbs:
      - get
      - list