apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: project-onboarding-operator-controller-manager
  name: controller-manager-metrics-reader-token
type: kubernetes.io/service-account-token
