apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: project-onboarding-operator
  name: project-onboarding-operator-tshirtsize-admin-role
rules:
- apiGroups:
  - onboarding.stderr.at
  resources:
  - tshirtsizes
  verbs:
  - '*'
- apiGroups:
  - onboarding.stderr.at
  resources:
  - tshirtsizes/status
  verbs:
  - get
