catalog_templates:
- channels: '[alpha]'
  replaces: hive-operator.v1.2.4863-e9ad0fa
  template_name: v4.12.yaml
- channels: '[alpha]'
  replaces: hive-operator.v1.2.4863-e9ad0fa
  template_name: v4.13.yaml
- channels: '[alpha]'
  replaces: hive-operator.v1.2.4863-e9ad0fa
  template_name: v4.14.yaml
- channels: '[alpha]'
  replaces: hive-operator.v1.2.4863-e9ad0fa
  template_name: v4.15.yaml
- channels: '[alpha]'
  replaces: hive-operator.v1.2.4863-e9ad0fa
  template_name: v4.16.yaml
- channels: '[alpha]'
  replaces: hive-operator.v1.2.4863-e9ad0fa
  template_name: v4.17.yaml
- channels: '[alpha]'
  replaces: hive-operator.v1.2.4863-e9ad0fa
  template_name: v4.18.yaml
- channels: '[alpha]'
  replaces: hive-operator.v1.2.4863-e9ad0fa
  template_name: v4.19.yaml
