apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: 3scale-api-management
    control-plane: controller-manager
  name: threescale-operator-controller-manager-metrics-service
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    app: 3scale-api-management
    control-plane: controller-manager
status:
  loadBalancer: {}
