apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: codeflare-operator
    app.kubernetes.io/part-of: codeflare
  name: codeflare-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
