apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    rbac.ext-remediation/aggregate-to-ext-remediation: "true"
  name: machine-deletion-remediation-machine-deletion-remediation-ext-remediation
rules:
- apiGroups:
  - machine-deletion-remediation.medik8s.io
  resources:
  - machinedeletionremediationtemplates
  verbs:
  - get
- apiGroups:
  - machine-deletion-remediation.medik8s.io
  resources:
  - machinedeletionremediations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
