---
catalog_templates:
  - template_name: v4.16.yaml
    channels: [preview]
    replaces: layer7-operator.v1.2.0
  - template_name: v4.17.yaml
    channels: [preview]
    replaces: layer7-operator.v1.2.0
  - template_name: v4.18.yaml
    channels: [preview]
    replaces: layer7-operator.v1.2.0
  - template_name: v4.19.yaml
    channels: [preview]
    replaces: layer7-operator.v1.2.0
