---
catalog_templates:
  - template_name: basic.yaml
    channels: [alpha]
    defaultChannel: alpha
    replaces: mirror-operator.v0.1.6
    skips:
      - mirror-operator.v0.1.4
      - mirror-operator.v0.1.5
