apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: nfs-provisioner-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
