apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: annotationlab-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: annotationlab-proxy-role
subjects:
- kind: ServiceAccount
  name: annotationlab-operator
  namespace: annotationlab-system
