catalog_templates:
- template_name: 4.17.yaml
  channels:
  - stable
  replaces: rabbitmq-cluster-operator.v2.18.0
- template_name: 4.18.yaml
  channels:
  - stable
  replaces: rabbitmq-cluster-operator.v2.18.0
- template_name: 4.19.yaml
  channels:
  - stable
  replaces: rabbitmq-cluster-operator.v2.18.0
- template_name: 4.20.yaml
  channels:
  - stable
  replaces: rabbitmq-cluster-operator.v2.18.0
