apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8383
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: b9d51391.open-cluster-management.io
kind: ConfigMap
metadata:
  name: manager-config
