catalog_templates:
  - template_name: latest.yaml
    channels:
      - stable
    replaces: victoriametrics-operator.v0.68.4
  - template_name: v4.12-v4.16.yaml
    channels:
      - stable
    replaces: victoriametrics-operator.v0.68.4
