apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: keycloakauthorizations.keycloak.nerc.mghpcc.org
spec:
  group: keycloak.nerc.mghpcc.org
  names:
    kind: KeycloakAuthorization
    listKind: KeycloakAuthorizationList
    plural: keycloakauthorizations
    singular: keycloakauthorization
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: |
          KeycloakAuthorization is the Schema for the keycloakauthorizations API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of KeycloakAuthorization
            properties:
              cleanupUndefinedAuthorizations:
                default: false
                type: boolean
              keycloak:
                properties:
                  adminSecret:
                    properties:
                      name:
                        default: keycloak-initial-admin
                        type: string
                      passwordKey:
                        default: password
                        type: string
                      usernameKey:
                        default: username
                        type: string
                    type: object
                  baseUrl:
                    description: 'Example: https://keycloak.apps-crc.testing'
                    type: string
                type: object
              managementState:
                default: Managed
                type: string
              realm:
                properties:
                  clients:
                    items:
                      properties:
                        authorizationSettings:
                          properties:
                            permissions:
                              items:
                                properties:
                                  name:
                                    type: string
                                  policy:
                                    type: string
                                  resource:
                                    type: string
                                  scope:
                                    type: string
                                type: object
                              type: array
                            policies:
                              items:
                                properties:
                                  config:
                                    properties:
                                      groups:
                                        type: string
                                    type: object
                                  decisionStrategy:
                                    enum:
                                    - UNANIMOUS
                                    - AFFIRMATIVE
                                    type: string
                                  description:
                                    type: string
                                  id:
                                    type: string
                                  logic:
                                    enum:
                                    - POSITIVE
                                    - NEGATIVE
                                    type: string
                                  name:
                                    type: string
                                  type:
                                    description: Only use one of the following policy
                                      types (aggregated, client, client-scope, group,
                                      regex, role, time, user)
                                    properties:
                                      aggregated:
                                        properties:
                                          policies:
                                            description: array of policy ids
                                            items:
                                              type: string
                                            type: array
                                        type: object
                                      client:
                                        properties:
                                          clients:
                                            items:
                                              type: string
                                            type: array
                                        type: object
                                      client-scope:
                                        properties:
                                          clientScopes:
                                            items:
                                              properties:
                                                id:
                                                  type: string
                                                required:
                                                  type: boolean
                                              type: object
                                            type: array
                                        type: object
                                      group:
                                        properties:
                                          groups:
                                            items:
                                              properties:
                                                extendChildren:
                                                  type: boolean
                                                id:
                                                  type: string
                                              type: object
                                            type: array
                                          groupsClaim:
                                            type: string
                                        type: object
                                      regex:
                                        properties:
                                          pattern:
                                            type: string
                                          targetClaim:
                                            type: string
                                          targetContextAttributes:
                                            type: boolean
                                        type: object
                                      role:
                                        properties:
                                          roles:
                                            items:
                                              properties:
                                                id:
                                                  type: string
                                                required:
                                                  type: boolean
                                              type: object
                                            type: array
                                        type: object
                                      time:
                                        properties:
                                          dayMonth:
                                            type: number
                                          dayMonthEnd:
                                            type: number
                                          hour:
                                            type: number
                                          hourEnd:
                                            type: number
                                          minute:
                                            type: number
                                          minuteEnd:
                                            type: number
                                          month:
                                            type: number
                                          monthEnd:
                                            type: number
                                          notAfter:
                                            description: "2024-04-26T00:00:00Z"
                                            type: string
                                          notBefore:
                                            description: "2024-04-25T00:00:00Z"
                                            type: string
                                          notOnOrAfter:
                                            description: "2024-04-26T00:00:00Z"
                                            type: string
                                        type: object
                                      user:
                                        properties:
                                          users:
                                            items:
                                              type: string
                                            type: array
                                        type: object
                                    type: object
                                type: object
                              type: array
                            resources:
                              items:
                                properties:
                                  attributes:
                                    items:
                                      type: object
                                      x-kubernetes-preserve-unknown-fields: true
                                    type: array
                                  displayName:
                                    type: string
                                  iconUri:
                                    type: string
                                  name:
                                    type: string
                                  scopes:
                                    items:
                                      properties:
                                        displayName:
                                          type: string
                                        id:
                                          type: string
                                        name:
                                          type: string
                                      type: object
                                    type: array
                                  scopesUma:
                                    items:
                                      properties:
                                        displayName:
                                          type: string
                                        id:
                                          type: string
                                        name:
                                          type: string
                                      type: object
                                    type: array
                                  type:
                                    type: string
                                  uri:
                                    type: string
                                  uris:
                                    items:
                                      type: string
                                    type: array
                                type: object
                              type: array
                          type: object
                        id:
                          type: string
                      type: object
                    type: array
                  id:
                    type: string
                type: object
              validateCerts:
                default: true
                type: boolean
            type: object
          status:
            description: Status defines the observed state of KeycloakAuthorization
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
