apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: fpga-dfl-manager-role
rules:
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - privileged
  resources:
  - leases
  verbs:
  - use
- apiGroups:
  - fpga.silicom.dk
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fpga.silicom.dk
  resources:
  - fpgadflnodes
  - fpgadflnodes/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fpga.silicom.dk
  resources:
  - fpgadfloperators/finalizers
  verbs:
  - update
- apiGroups:
  - fpga.silicom.dk
  resources:
  - fpgadfloperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
