apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: fpga-dfl-fpgadflconfig-viewer-role
rules:
- apiGroups:
  - fpga.silicom.dk
  resources:
  - fpgadflconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fpga.silicom.dk
  resources:
  - fpgadflconfigs/status
  verbs:
  - get
