apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: fpga-dfl-fpgadfloperator-viewer-role
rules:
- apiGroups:
  - fpga.silicom.dk
  resources:
  - fpgadfloperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fpga.silicom.dk
  resources:
  - fpgadfloperators/status
  verbs:
  - get
