apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/name: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  name: amd-gpu-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
