apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/name: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  name: amd-gpu-operator-node-labeller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: amd-gpu-operator-node-labeller
subjects:
- kind: ServiceAccount
  name: amd-gpu-operator-node-labeller
  namespace: openshift-amd-gpu
