apiVersion: v1
data:
  controller_manager_config.yaml: |
    healthProbeBindAddress: :8081
    metricsBindAddress: 127.0.0.1:8080
    leaderElection:
      enabled: true
      resourceID: gpue.openshift.io
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/name: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  name: amd-gpu-operator-manager-config
