---
catalog_templates:
  - template_name: v4.12.yaml
    channels: [alpha]
    replaces: multi-nic-cni-operator.v1.2.7
  - template_name: v4.13.yaml
    channels: [alpha]
    replaces: multi-nic-cni-operator.v1.2.7
  - template_name: v4.14.yaml
    channels: [alpha]
    replaces: multi-nic-cni-operator.v1.2.7
  - template_name: v4.15.yaml
    channels: [alpha]
    replaces: multi-nic-cni-operator.v1.2.7
  - template_name: v4.16.yaml
    channels: [alpha]
    replaces: multi-nic-cni-operator.v1.2.7
  - template_name: v4.17.yaml
    channels: [alpha]
    replaces: multi-nic-cni-operator.v1.2.7
  - template_name: v4.18.yaml
    channels: [alpha]
    replaces: multi-nic-cni-operator.v1.2.7
  - template_name: v4.19.yaml
    channels: [alpha]
    replaces: multi-nic-cni-operator.v1.2.7
