apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: sts-tsync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sts-tsync
subjects:
- kind: ServiceAccount
  name: sts-tsync
  namespace: sts-silicom
