apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    crowdstrike.com/component: kube-rbac-proxy
    crowdstrike.com/created-by: falcon-operator
    crowdstrike.com/instance: metrics-reader
    crowdstrike.com/managed-by: kustomize
    crowdstrike.com/name: clusterrole
    crowdstrike.com/part-of: Falcon
    crowdstrike.com/provider: crowdstrike
  name: falcon-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
