---
catalog_templates:
  - template_name: v4.12.yaml
    channels: [stable]
    replaces: infinispan-operator.v2.5.6
    skipRange: '>=2.4.18 <2.5.7'

  - template_name: v4.13.yaml
    channels: [stable]
    replaces: infinispan-operator.v2.5.6
    skipRange: '>=2.4.18 <2.5.7'

  - template_name: v4.14.yaml
    channels: [stable]
    replaces: infinispan-operator.v2.5.6
    skipRange: '>=2.4.18 <2.5.7'

  - template_name: v4.15.yaml
    channels: [stable]
    replaces: infinispan-operator.v2.5.6
    skipRange: '>=2.4.18 <2.5.7'

  - template_name: v4.16.yaml
    channels: [stable]
    replaces: infinispan-operator.v2.5.6
    skipRange: '>=2.4.18 <2.5.7'

  - template_name: v4.17.yaml
    channels: [stable]
    replaces: infinispan-operator.v2.5.6
    skipRange: '>=2.4.18 <2.5.7'

  - template_name: v4.18.yaml
    channels: [stable]
    replaces: infinispan-operator.v2.5.6
    skipRange: '>=2.4.18 <2.5.7'

  - template_name: v4.19.yaml
    channels: [stable]
    replaces: infinispan-operator.v2.5.6
    skipRange: '>=2.4.18 <2.5.7'

  - template_name: v4.20.yaml
    channels: [stable]
    replaces: infinispan-operator.v2.5.6
    skipRange: '>=2.4.18 <2.5.7'

  - template_name: v4.21.yaml
    channels: [stable]
    replaces: infinispan-operator.v2.5.6
    skipRange: '>=2.4.18 <2.5.7'

  - template_name: v4.22.yaml
    channels: [stable]
    replaces: infinispan-operator.v2.5.6
    skipRange: '>=2.4.18 <2.5.7'
