apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: codeflare-operator
    app.kubernetes.io/part-of: codeflare
  name: codeflare-operator-manager-edit-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: codeflare-operator-controller-manager
  namespace: openshift-operators
