apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.istio.io/v1alpha1",
          "kind": "Istio",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "sailoperator",
              "app.kubernetes.io/instance": "istio-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "istio",
              "app.kubernetes.io/part-of": "sailoperator"
            },
            "name": "istio-sample"
          },
          "spec": {
            "values": {
              "cni": {
                "chained": false,
                "cniBinDir": "/var/lib/cni/bin",
                "cniConfDir": "/etc/cni/multus/net.d",
                "cniConfFileName": "istio-cni.conf",
                "excludeNamespaces": [
                  "istio-system",
                  "kube-system"
                ],
                "logLevel": "info",
                "privileged": true,
                "provider": "multus"
              },
              "global": {
                "platform": "openshift"
              },
              "istio_cni": {
                "chained": false,
                "enabled": true
              }
            },
            "version": "v3.0"
          }
        }
      ]
    capabilities: Seamless Upgrades
    categories: OpenShift Optional, Integration & Delivery, Networking, Security
    containerImage: quay.io/maistra-dev/istio-ubi9-operator:3.0-nightly-2023-09-24
    createdAt: "2023-09-24T03:38:27Z"
    operators.operatorframework.io/builder: operator-sdk-v1.28.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: sailoperator.v3.0.0-nightly-2023-09-24
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: AuthorizationPolicy
      name: authorizationpolicies.security.istio.io
      version: v1
    - kind: AuthorizationPolicy
      name: authorizationpolicies.security.istio.io
      version: v1beta1
    - kind: DestinationRule
      name: destinationrules.networking.istio.io
      version: v1alpha3
    - kind: DestinationRule
      name: destinationrules.networking.istio.io
      version: v1beta1
    - kind: EnvoyFilter
      name: envoyfilters.networking.istio.io
      version: v1alpha3
    - kind: Gateway
      name: gateways.networking.istio.io
      version: v1alpha3
    - kind: Gateway
      name: gateways.networking.istio.io
      version: v1beta1
    - description: Istio represents an Istio Service Mesh deployment
      displayName: Istio
      kind: Istio
      name: istios.operator.istio.io
      version: v1alpha1
    - kind: PeerAuthentication
      name: peerauthentications.security.istio.io
      version: v1beta1
    - kind: ProxyConfig
      name: proxyconfigs.networking.istio.io
      version: v1beta1
    - kind: RequestAuthentication
      name: requestauthentications.security.istio.io
      version: v1
    - kind: RequestAuthentication
      name: requestauthentications.security.istio.io
      version: v1beta1
    - kind: ServiceEntry
      name: serviceentries.networking.istio.io
      version: v1alpha3
    - kind: ServiceEntry
      name: serviceentries.networking.istio.io
      version: v1beta1
    - kind: Sidecar
      name: sidecars.networking.istio.io
      version: v1alpha3
    - kind: Sidecar
      name: sidecars.networking.istio.io
      version: v1beta1
    - kind: Telemetry
      name: telemetries.telemetry.istio.io
      version: v1alpha1
    - kind: VirtualService
      name: virtualservices.networking.istio.io
      version: v1alpha3
    - kind: VirtualService
      name: virtualservices.networking.istio.io
      version: v1beta1
    - kind: WasmPlugin
      name: wasmplugins.extensions.istio.io
      version: v1alpha1
    - kind: WorkloadEntry
      name: workloadentries.networking.istio.io
      version: v1alpha3
    - kind: WorkloadEntry
      name: workloadentries.networking.istio.io
      version: v1beta1
    - kind: WorkloadGroup
      name: workloadgroups.networking.istio.io
      version: v1alpha3
    - kind: WorkloadGroup
      name: workloadgroups.networking.istio.io
      version: v1beta1
  description: |-
    This is an experimental operator for installing Istio service mesh.

    [See this page](https://github.com/maistra/istio-operator/blob/maistra-3.0/bundle/README.md) for instructions on how to use it.
  displayName: Sail Operator
  icon:
  - base64data: |-
      iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAAAFiAAABYgFfJ9BTAAAH
      L0lEQVR4nO2du24bRxSGz5LL+01kaMuX2HShnmlSi2VUBM4bKG/gdGFnl+rsBwggvUHUsTT9AIGd
      noWCIIWNIJZNWKLM5Uww1K4sC6JEQrP7z8yeDyDYCHuG3F/nNmeWnpSSTMXvD3tE9Ey9gp3e0NiF
      WkzGgqVvEtFLvz/c8/vDNQPW4xQ2CCBim4gO/P7wFzOW4wY2CUDRIKLnfn/4xu8PvzNgPdZjmwAi
      ukT02u8Pn5mxHHuxVQART9kb3AzbBUDsDW6GFgEMRuNHwM8QobzBkCuF1dDlAfYGo/GeAULYDCuF
      Hngd1qAzBKgy7c1gNEa74kbYN+CQsAS6cwD15T8djMZKCOj/QhUS9jkkXE1cSaBKzF4ORuMXg9EY
      eQMeE9GQq4TFxF0FPAnDAtIbdEMRcF5wCUmUgZ3QGyBjcpQX/Axcg5Ek2QeIcgNkpbDLyeHXJN0I
      6oYh4aeE7Z5HJYd7QPtGgegEKnf8OzgkbLMITkG2glVI2AdWCXMRpL1MRO8FzMs0pAjCCiG1IjBh
      M0jlBQeD0RhVq3fTLAJTdgMboSeAigBkG4pJ28FKBK8HozGqVu+mMTE0cR5gFyiC1FUHpg6EsAgS
      wuSJoN3t7+//ALK9nZbpY6NHwh7drf8qG+VjkPnnadg7MFoA+bxPYn2tBBTBrutbyVYMhc5FUMih
      zDs9T2DNVLB42D4GiUCVp862jO0ZC/e8knjYnlAGsmTVKHKyMrDrXIDnFWedW/+BRPDYxVkC+w6G
      5LItca/5L8i6miVAzjJox8qTQbJcaIt2/QPIvMoHTDgIowVrj4bJVrUhq8UjgGmVFO4D7MaC1WcD
      xd2mR7kswrTaOHqBMKwbuw+Hel5p9m0blRQ+cWHU3P7TwSopvFVHJYXWnzxy4Xg4yUa5DcwHrO4P
      OCEAOs0HMsD+gLWloTMCUE0i8eAbVCiwtlXsjgBUKCjk2rJZnQBMWxsKnBKAQrRrAlQaWhkKnBMA
      eV5Z3GtxKFgS9wQQhQLMEIkKBVY1iJwUgELcbnigqmDbpgaRswKYVwV31t6CrFvjBdwVgAoF1eK6
      LBcQpru2TBU7LQCFuLOGSgif2ZAQOi8A8rOcEF6B+wLAJ4RGTxSnQgDzhLBVRU0QGe0F0iEAlRA2
      KzlQh3DT5LIwNQKYdwhvNbgsvEB6BBCWhcARMiPPGaZKAAqgFzDyTEHqBAD0Ah0TvUDqBEDsBb4i
      lQJgL/CFVAqA2AuckVoBsBc4JbUCUIhGBdUdNMYLpFoAslnJg/YIOqbMD6ZaAOpomawVUc8fMmJe
      IN0CmE8R1z+DTBuxR5B6AVA2o46Zo6zDk0EWwOmzBv4Gmd5GP2yCBaAEUMw/AJWEhPYCLIAQYEkI
      TQZZACFyrSxAphvIxhALICKTaaYxGWQBnEM2yqhkcBM1PMoCOIesFB+AOoOEygVYABcAdgYhrWEW
      wAVEq4YSACQZZAFcJJdtAXsCiXsBFsAlyFrpPcj046Q7gyyASxBrlRnQfKJegAVwGX62nZbWMAtg
      AcAw0E2yJ8ACWIColxFPHo1IzAuwABaR9+8Dm0KJ5QEsgCsANoU6SYUBFsAVyGoR9XgZSioMsACu
      QP00DdB8ImGABXAVamoY94OViYQBFsA1yHoJdYRMEfvUMAvgGmSlGADNx54HsACuA1sOduPeG2AB
      LIEs55HmYw0DLIAlkNXiP0DzsVYDLIAlkKU8Mg9gDwAn53eAS2jEeYaQBbAkoKeOR7AA0MhKAdkP
      iC0PYAEsSymPOkZOYTkYy6PnWQBLon6HCLyEWMIAC2BZPK8EHBMjFoABADeGiAVgALJc+Au4iljy
      ABbAKhRz6O9LuxdgAayAzPtV8BK0zwewAFYhk2mCV8AeAA24I7ip+4IsgFXJZVGTwnN0j4mxAFZE
      FnLvwEtgAUBxrBJgAayIzGZQTxOLYA8Axc/eAa+gq/Nivs6LOUMwe0tCBt7RSUBSFr1PJ+vqo3lH
      J+oNWgZQmAgGO703Wq6l4yLWoW6wlBPv+LMf3ugOCUneZEok5h5+3fCPpMIAC2AhQrynmfjofQ4y
      NJ0J72R6m6azkjcNiKbzh3+YfoOvQ9uouJ0CkPKYgtk7byYyNJkKL5jVaTJt0kyQdzJVf9EMX66i
      rRIwWQCv3n+ctLzDT/WzOPzlBpfU2Tn8EmE44QH+JKLDMJadvW9t1IbRH/z42x+9DNFL4BpNRZv4
      4xSA2js/OPc6u9FbG7XDGO2mAjUqHuz0hjf9rLoEsBe+5jd8a6N2oOm6zGK0DIdoEcDWRm1Px3WY
      lVCl4P5NvzLuBNqLFg/AArAXLXsC3Ao2m0srJfUe7PS0JNIsACwXK6WzV7DTSySRZgHEy4fL/nuT
      vMHXwQK4Oa/CKwzP32hdu3VxwwK4notxeN580dGEMQEWwJc4HFuiZTJpEEAUh2GJlsm4IIBFiZY1
      cRiJLQI4n2iRa3EYBhH9D18eNW58bi76AAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          - validatingwebhookconfigurations
          verbs:
          - '*'
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - autoscaling
          resources:
          - horizontalpodautoscalers
          verbs:
          - '*'
        - apiGroups:
          - k8s.cni.cncf.io
          resources:
          - network-attachment-definitions
          verbs:
          - '*'
        - apiGroups:
          - networking.istio.io
          resources:
          - envoyfilters
          verbs:
          - '*'
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - '*'
        - apiGroups:
          - operator.istio.io
          resources:
          - istios
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operator.istio.io
          resources:
          - istios/finalizers
          verbs:
          - update
        - apiGroups:
          - operator.istio.io
          resources:
          - istios/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          - rolebindings
          - roles
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: istio-operator
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: sailoperator
          app.kubernetes.io/instance: istio-operator
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: sailoperator
          control-plane: istio-operator
        name: istio-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/created-by: sailoperator
              app.kubernetes.io/part-of: sailoperator
              control-plane: istio-operator
          strategy: {}
          template:
            metadata:
              annotations:
                images3_0.cni: quay.io/maistra-dev/install-cni:3.0-nightly-2023-09-24
                images3_0.istiod: quay.io/maistra-dev/pilot:3.0-nightly-2023-09-24
                images3_0.proxy: quay.io/maistra-dev/proxyv2:3.0-nightly-2023-09-24
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/created-by: sailoperator
                app.kubernetes.io/part-of: sailoperator
                control-plane: istio-operator
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                command:
                - /manager
                env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/maistra-dev/istio-ubi9-operator:3.0-nightly-2023-09-24
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                volumeMounts:
                - mountPath: /etc/istio-operator
                  name: operator-config
                  readOnly: true
              securityContext:
                runAsNonRoot: true
              serviceAccountName: istio-operator
              terminationGracePeriodSeconds: 10
              volumes:
              - downwardAPI:
                  defaultMode: 420
                  items:
                  - fieldRef:
                      fieldPath: metadata.annotations
                    path: config.properties
                name: operator-config
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: istio-operator
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - istio
  - maistra
  - servicemesh
  - envoy
  links:
  - name: Istio Project
    url: https://istio.io
  maintainers:
  - email: istio-feedback@redhat.com
    name: OpenShift Service Mesh Team
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 3.0.0-nightly-2023-09-24
