apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: sailoperator
    app.kubernetes.io/instance: istio-operator-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: sailoperator
    control-plane: istio-operator
  name: istio-operator-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/created-by: sailoperator
    app.kubernetes.io/part-of: sailoperator
    control-plane: istio-operator
status:
  loadBalancer: {}
