apiVersion: v1
data:
  bpfd.agent.image: quay.io/bpfd/bpfd-agent:latest
  bpfd.agent.log.level: info
  bpfd.enable.csi: "false"
  bpfd.image: quay.io/bpfd/bpfd:latest
  bpfd.log.level: info
  bpfd.toml: |
    [[grpc.endpoints]]
    type = "unix"
    path = "/bpfd-sock/bpfd.sock"
    enabled = true
kind: ConfigMap
metadata:
  name: bpfd-config
