apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: migrationcontrollers.migration.openshift.io
spec:
  conversion:
    strategy: None
  group: migration.openshift.io
  names:
    kind: MigrationController
    listKind: MigrationControllerList
    plural: migrationcontrollers
    singular: migrationcontroller
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: MigrationController is the Schema for the MigrationControllers
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MigrationController defines the desired state
              of MigrationController
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: MigrationControllerStatus defines the observed state
              of MigrationController
            properties:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
        x-kubernetes-preserve-unknown-fields: true
