apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cert-utils-operator-certificate-rule-alerts
spec:
  groups:
  - name: cert-utils-operator-recording-rules
    rules:
    - expr: certutils_certificate_expiry_time - certutils_certificate_issue_time
      record: cert:validity_duration:sec
    - expr: certutils_certificate_expiry_time - time()
      record: cert:time_to_expiration:sec
  - name: cert-utils-operator-alerting-rules
    rules:
    - alert: CertificateApproachingExpiration
      annotations:
        message: Certificate {{ $labels.namespace }}/{{ $labels.name }} is at 85%
          of its lifetime
        summary: Certificate {{ $labels.namespace }}/{{ $labels.name }} is at 85%
          of its lifetime
      expr: |
        cert:time_to_expiration:sec/cert:validity_duration:sec < 0.15
      labels:
        severity: warning
    - alert: CertificateIsAboutToExpire
      annotations:
        message: Certificate {{ $labels.namespace }}/{{ $labels.name }} is at 95%
          of its lifetime
        summary: Certificate {{ $labels.namespace }}/{{ $labels.name }} is at 95%
          of its lifetime
      expr: |
        cert:time_to_expiration:sec/cert:validity_duration:sec < 0.05
      labels:
        severity: critical
