apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: annotationlab-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: annotationlab-leader-election-role
subjects:
- kind: ServiceAccount
  name: annotationlab-operator
  namespace: annotationlab-system
