apiVersion: v1
data:
  bpfd.agent.image: quay.io/bpfd/bpfd-agent:v0.2.1
  bpfd.image: quay.io/bpfd/bpfd:v0.2.1
  bpfd.log.level: info
  bpfd.toml: |
    [tls] # REQUIRED
    ca_cert = "/etc/bpfd/certs/ca/ca.crt"
    cert = "/etc/bpfd/certs/bpfd/tls.crt"
    key = "/etc/bpfd/certs/bpfd/tls.key"
    client_cert = "/etc/bpfd/certs/bpfd-client/tls.crt"
    client_key = "/etc/bpfd/certs/bpfd-client/tls.key"
kind: ConfigMap
metadata:
  name: bpfd-config
