apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: gitops-primer-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: export-webhook
status:
  loadBalancer: {}
