---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/part-of: coherence-operator
    app.kubernetes.io/version: 3.5.5
    control-plane: coherence
  name: coherence-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coherence-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
