apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  creationTimestamp: null
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    release: istio
  name: workloadentries.networking.istio.io
spec:
  group: networking.istio.io
  names:
    categories:
    - istio-io
    - networking-istio-io
    kind: WorkloadEntry
    listKind: WorkloadEntryList
    plural: workloadentries
    shortNames:
    - we
    singular: workloadentry
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: 'CreationTimestamp is a timestamp representing the server time
        when this object was created. It is not guaranteed to be set in happens-before
        order across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
        lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Address associated with the network endpoint.
      jsonPath: .spec.address
      name: Address
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: 'Configuration affecting VMs onboarded into the mesh. See
              more details at: https://istio.io/docs/reference/config/networking/workload-entry.html'
            properties:
              address:
                description: Address associated with the network endpoint without
                  the port.
                maxLength: 256
                type: string
                x-kubernetes-validations:
                - message: UDS must be an absolute path or abstract socket
                  rule: 'self.startsWith(''unix://'') ? (self.substring(7,8) == ''/''
                    || self.substring(7,8) == ''@'') : true'
                - message: UDS may not be a dir
                  rule: 'self.startsWith(''unix://'') ? !self.endsWith(''/'') : true'
              labels:
                additionalProperties:
                  type: string
                description: One or more labels associated with the endpoint.
                maxProperties: 256
                type: object
              locality:
                description: The locality associated with the endpoint.
                maxLength: 2048
                type: string
              network:
                description: Network enables Istio to group endpoints resident in
                  the same L3 domain/network.
                maxLength: 2048
                type: string
              ports:
                additionalProperties:
                  maximum: 4294967295
                  minimum: 0
                  type: integer
                  x-kubernetes-validations:
                  - message: port must be between 1-65535
                    rule: 0 < self && self <= 65535
                description: Set of ports associated with the endpoint.
                maxProperties: 128
                type: object
                x-kubernetes-validations:
                - message: port name must be valid
                  rule: self.all(key, size(key) < 63 && key.matches('^[a-zA-Z0-9](?:[-a-zA-Z0-9]*[a-zA-Z0-9])?$'))
              serviceAccount:
                description: The service account associated with the workload if a
                  sidecar is present in the workload.
                maxLength: 253
                type: string
              weight:
                description: The load balancing weight associated with the endpoint.
                maximum: 4294967295
                minimum: 0
                type: integer
            type: object
            x-kubernetes-validations:
            - message: Address is required
              rule: has(self.address) || has(self.network)
            - message: UDS may not include ports
              rule: '(has(self.address) && self.address.startsWith(''unix://'')) ?
                !has(self.ports) : true'
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - spec
        - spec
        - spec
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - description: 'CreationTimestamp is a timestamp representing the server time
        when this object was created. It is not guaranteed to be set in happens-before
        order across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
        lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Address associated with the network endpoint.
      jsonPath: .spec.address
      name: Address
      type: string
    name: v1alpha3
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: 'Configuration affecting VMs onboarded into the mesh. See
              more details at: https://istio.io/docs/reference/config/networking/workload-entry.html'
            properties:
              address:
                description: Address associated with the network endpoint without
                  the port.
                maxLength: 256
                type: string
                x-kubernetes-validations:
                - message: UDS must be an absolute path or abstract socket
                  rule: 'self.startsWith(''unix://'') ? (self.substring(7,8) == ''/''
                    || self.substring(7,8) == ''@'') : true'
                - message: UDS may not be a dir
                  rule: 'self.startsWith(''unix://'') ? !self.endsWith(''/'') : true'
              labels:
                additionalProperties:
                  type: string
                description: One or more labels associated with the endpoint.
                maxProperties: 256
                type: object
              locality:
                description: The locality associated with the endpoint.
                maxLength: 2048
                type: string
              network:
                description: Network enables Istio to group endpoints resident in
                  the same L3 domain/network.
                maxLength: 2048
                type: string
              ports:
                additionalProperties:
                  maximum: 4294967295
                  minimum: 0
                  type: integer
                  x-kubernetes-validations:
                  - message: port must be between 1-65535
                    rule: 0 < self && self <= 65535
                description: Set of ports associated with the endpoint.
                maxProperties: 128
                type: object
                x-kubernetes-validations:
                - message: port name must be valid
                  rule: self.all(key, size(key) < 63 && key.matches('^[a-zA-Z0-9](?:[-a-zA-Z0-9]*[a-zA-Z0-9])?$'))
              serviceAccount:
                description: The service account associated with the workload if a
                  sidecar is present in the workload.
                maxLength: 253
                type: string
              weight:
                description: The load balancing weight associated with the endpoint.
                maximum: 4294967295
                minimum: 0
                type: integer
            type: object
            x-kubernetes-validations:
            - message: Address is required
              rule: has(self.address) || has(self.network)
            - message: UDS may not include ports
              rule: '(has(self.address) && self.address.startsWith(''unix://'')) ?
                !has(self.ports) : true'
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - spec
        - spec
        - spec
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - description: 'CreationTimestamp is a timestamp representing the server time
        when this object was created. It is not guaranteed to be set in happens-before
        order across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
        lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Address associated with the network endpoint.
      jsonPath: .spec.address
      name: Address
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: 'Configuration affecting VMs onboarded into the mesh. See
              more details at: https://istio.io/docs/reference/config/networking/workload-entry.html'
            properties:
              address:
                description: Address associated with the network endpoint without
                  the port.
                maxLength: 256
                type: string
                x-kubernetes-validations:
                - message: UDS must be an absolute path or abstract socket
                  rule: 'self.startsWith(''unix://'') ? (self.substring(7,8) == ''/''
                    || self.substring(7,8) == ''@'') : true'
                - message: UDS may not be a dir
                  rule: 'self.startsWith(''unix://'') ? !self.endsWith(''/'') : true'
              labels:
                additionalProperties:
                  type: string
                description: One or more labels associated with the endpoint.
                maxProperties: 256
                type: object
              locality:
                description: The locality associated with the endpoint.
                maxLength: 2048
                type: string
              network:
                description: Network enables Istio to group endpoints resident in
                  the same L3 domain/network.
                maxLength: 2048
                type: string
              ports:
                additionalProperties:
                  maximum: 4294967295
                  minimum: 0
                  type: integer
                  x-kubernetes-validations:
                  - message: port must be between 1-65535
                    rule: 0 < self && self <= 65535
                description: Set of ports associated with the endpoint.
                maxProperties: 128
                type: object
                x-kubernetes-validations:
                - message: port name must be valid
                  rule: self.all(key, size(key) < 63 && key.matches('^[a-zA-Z0-9](?:[-a-zA-Z0-9]*[a-zA-Z0-9])?$'))
              serviceAccount:
                description: The service account associated with the workload if a
                  sidecar is present in the workload.
                maxLength: 253
                type: string
              weight:
                description: The load balancing weight associated with the endpoint.
                maximum: 4294967295
                minimum: 0
                type: integer
            type: object
            x-kubernetes-validations:
            - message: Address is required
              rule: has(self.address) || has(self.network)
            - message: UDS may not include ports
              rule: '(has(self.address) && self.address.startsWith(''unix://'')) ?
                !has(self.ports) : true'
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - spec
        - spec
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
