catalog_templates:
  - template_name: v4.12-v4.16.yaml
    channels: [beta]
    replaces: victoriametrics-operator.v0.57.0
  - template_name: v4.17-v4.18.yaml
    channels: [beta]
    replaces: victoriametrics-operator.v0.57.0
