apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kubernaut-operator
  name: kubernaut-operator-kubernaut-admin-role
rules:
- apiGroups:
  - kubernaut.ai
  resources:
  - kubernauts
  verbs:
  - '*'
- apiGroups:
  - kubernaut.ai
  resources:
  - kubernauts/status
  verbs:
  - get
