apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: servicemeshoperator3
    app.kubernetes.io/instance: servicemesh-operator3-metrics-service
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: servicemeshoperator3
    control-plane: servicemesh-operator3
  name: servicemesh-operator3-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/created-by: servicemeshoperator3
    app.kubernetes.io/part-of: servicemeshoperator3
    control-plane: servicemesh-operator3
status:
  loadBalancer: {}
