---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rest
    app.kubernetes.io/instance: coherence-operator-rest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/part-of: coherence-operator
    app.kubernetes.io/version: 3.5.2
    control-plane: coherence
  name: coherence-operator-rest
spec:
  ports:
  - name: http-rest
    port: 8000
    targetPort: operator
  selector:
    app.kubernetes.io/component: manager
    app.kubernetes.io/instance: coherence-operator-manager
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/version: 3.5.2
    control-plane: coherence
status:
  loadBalancer: {}
