apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kepler-operator
    control-plane: controller-manager
  name: kepler-operator-controller-manager-metrics-service
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: manager
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/part-of: kepler-operator
status:
  loadBalancer: {}
