---
catalog_templates:
  - template_name: v4.12.yaml
    channels: [alpha-1.2]
    replaces: multi-nic-cni-operator.1.2.5
  - template_name: v4.13.yaml
    channels: [alpha-1.2]
    replaces: multi-nic-cni-operator.1.2.5
  - template_name: v4.14.yaml
    channels: [alpha-1.2]
    replaces: multi-nic-cni-operator.1.2.5
  - template_name: v4.15.yaml
    channels: [alpha-1.2]
    replaces: multi-nic-cni-operator.1.2.5
  - template_name: v4.16.yaml
    channels: [alpha-1.2]
    replaces: multi-nic-cni-operator.1.2.5
  - template_name: v4.17.yaml
    channels: [alpha-1.2]
    replaces: multi-nic-cni-operator.1.2.5
