apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bindings.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: Binding
    listKind: BindingList
    plural: bindings
    singular: binding
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            apiSelector:
              properties:
                matchExpressions:
                  items:
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                      values:
                        type: array
                  type: array
                matchLabels:
                  type: object
              type: object
            credentialsRef:
              properties:
                name:
                  type: string
                namespace:
                  type: string
              type: object
          required:
          - credentialsRef
          type: object
        status:
          properties:
            currentState:
              type: string
            desiredState:
              type: string
            lastSync:
              properties:
                nanos:
                  type: integer
                seconds:
                  type: integer
              type: object
            previousState:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
