apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: limits.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: Limit
    listKind: LimitList
    plural: limits
    singular: limit
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            maxValue:
              format: int64
              type: integer
            metricRef:
              properties:
                apiVersion:
                  type: string
                fieldPath:
                  type: string
                kind:
                  type: string
                name:
                  type: string
                namespace:
                  type: string
                resourceVersion:
                  type: string
                uid:
                  type: string
              type: object
            period:
              type: string
          required:
          - period
          - maxValue
          - metricRef
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
