apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mappingrules.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: MappingRule
    listKind: MappingRuleList
    plural: mappingrules
    singular: mappingrule
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            increment:
              format: int64
              type: integer
            method:
              type: string
            metricRef:
              properties:
                apiVersion:
                  type: string
                fieldPath:
                  type: string
                kind:
                  type: string
                name:
                  type: string
                namespace:
                  type: string
                resourceVersion:
                  type: string
                uid:
                  type: string
              type: object
            path:
              type: string
          required:
          - path
          - method
          - increment
          - metricRef
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
