apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenants.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            email:
              type: string
            masterCredentialsRef:
              properties:
                name:
                  type: string
                namespace:
                  type: string
              type: object
            organizationName:
              type: string
            passwordCredentialsRef:
              properties:
                name:
                  type: string
                namespace:
                  type: string
              type: object
            systemMasterUrl:
              type: string
            tenantSecretRef:
              properties:
                name:
                  type: string
                namespace:
                  type: string
              type: object
            username:
              type: string
          required:
          - username
          - email
          - organizationName
          - systemMasterUrl
          - tenantSecretRef
          - passwordCredentialsRef
          - masterCredentialsRef
          type: object
        status:
          properties:
            adminId:
              format: int64
              type: integer
            tenantId:
              format: int64
              type: integer
          required:
          - tenantId
          - adminId
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
