apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: odf-node-recovery-operator-metrics-reader
  name: odf-node-recovery-operator-metrics-reader
type: kubernetes.io/service-account-token
