apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-global-hub-webhook-certs
  creationTimestamp: null
  labels:
    name: multicluster-global-hub-webhook
    service: multicluster-global-hub-webhook
  name: multicluster-global-hub-webhook
spec:
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    name: multicluster-global-hub-operator
status:
  loadBalancer: {}
