apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: codeflare-operator
    app.kubernetes.io/part-of: codeflare
  name: codeflare-operator-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: codeflare-operator
    app.kubernetes.io/part-of: codeflare
status:
  loadBalancer: {}
